apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- argocd-ns.yml
- argocd-ingress.yml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml

patchesStrategicMerge:
- ./argocd-cmd-params-configmap.yml
- ./delete-argocd-networkpolicy.yml