apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- argocd-ns.yml
- argocd-ingress.yml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml

patches:
  # refer to https://github.com/argoproj/argo-helm/issues/1471
  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/securityContext/seccompProfile/type
        value: "Unconfined"
      - op: replace
        path: /spec/template/spec/initContainers/0/securityContext/seccompProfile/type
        value: Unconfined
patchesStrategicMerge:
- ./argocd-cmd-params-configmap.yml