apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- argocd-ns.yml
- argocd-ingress.yml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml

patches:
- path: ./argocd-cmd-params-configmap.yml
- path: ./delete-application-controller-np.yml
- path: ./delete-notifications-controller-np.yml
- path: ./delete-repo-server-np.yml