apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agocd-apps
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/argocd-apps
    repoURL: 'https://github.com/yukin520/my-k8s.git'
    targetRevision: HEAD
  sources: []
  project: default