apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-resource
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/argocd
    repoURL: https://github.com/yukin520/my-k8s.git
    targetRevision: HEAD
  sources: []
  project: default
