apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/cloudfalred
    repoURL: 'https://github.com/yukin520/my-k8s.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null